# Generated by Django 6.1.1 on 2026-10-10 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0049_pendingreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='appcreaterequests',
            name='allow_community_distributions',
            field=models.BooleanField(default=False, verbose_name='Разрешить сторонние дистрибуции'),
        ),
        migrations.AddField(
            model_name='appeditrequests',
            name='allow_community_distributions',
            field=models.BooleanField(default=False, verbose_name='Разрешить сторонние дистрибуции'),
        ),
        migrations.AddField(
            model_name='application',
            name='allow_community_distributions',
            field=models.BooleanField(default=False, verbose_name='Разрешить сторонние дистрибуции'),
        ),
    ]
